### ISSUE TITLE
Address mobile input lag

### ISSUE THREAD

**Issue by Gwunhar** [adamculpepper/toggle-switchy#13]
On mobile the input suffers from the "300ms delay" issue as discussed in Slack.

**Comment by adamculpepper** [comment]
Apparently this wasn't an issue with the CSS code, but an issue with the demo page HTML. It ended up fixing itself when I added in `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">`.

Thanks for reporting this @Gwunhar! 😃 

Further reading on this issue: https://www.sitepoint.com/5-ways-prevent-300ms-click-delay-mobile-devices
